[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings for OpenZeppelin and Forge Std
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
